<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /Users/nicoleac/Documents/dev/aura-sphere/static/models/Aura.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube_7_1: THREE.Mesh
      Cube_6: THREE.Mesh
      Cube_3: THREE.Mesh
      Cube_3_1: THREE.Mesh
      Cube_3_2: THREE.Mesh
      Cube_2_1: THREE.Mesh
      Cube_2_2: THREE.Mesh
      Cube_2_3: THREE.Mesh
      Cube_2_4: THREE.Mesh
      Cube_11: THREE.Mesh
      Cube_9: THREE.Mesh
      Cube_11_1: THREE.Mesh
      Cube_10: THREE.Mesh
      Cube_11_2: THREE.Mesh
      Cube_8: THREE.Mesh
      Cube_7: THREE.Mesh
      Cube_5: THREE.Mesh
      Cube_4: THREE.Mesh
      Cube_2: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/models/Aura.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.DirectionalLight intensity={1} decay={2} rotation={[0.6, 0.6, -0.88]} />
      <T.DirectionalLight intensity={0.2} decay={2} rotation={[-2.04, -0.45, 1.35]} />
      <T.OrthographicCamera
        makeDefault={false}
        far={100000}
        near={0}
        position={[59.12, 85.53, 990.22]}
        rotation={[0.05, 0.1, 0]}
      />
      <T.Group position={[36.55, 363.2, -57.28]} scale={0.87}>
        <T.Mesh
          geometry={gltf.nodes.Cube_7_1.geometry}
          material={gltf.nodes.Cube_7_1.material}
          position={[-6.28, 14.31, 1.18]}
          rotation={[2.41, -0.08, 2.37]}
          scale={[0.84, 0.84, 2.22]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_6.geometry}
          material={gltf.nodes.Cube_6.material}
          position={[16.29, -21.48, 19.57]}
          rotation={[1.12, 0.23, -0.91]}
          scale={[0.64, 0.64, 1.7]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_3.geometry}
          material={gltf.nodes.Cube_3.material}
          position={[16.75, 21.21, 17.47]}
          rotation={[-0.12, -0.26, -0.5]}
          scale={[0.43, 0.55, 0.39]}
        />
      </T.Group>
      <T.Group position={[-54.8, 310.45, 15.76]} rotation={[0, -0.2, -0.21]} scale={[-0.9, 0.87, 0.87]}>
        <T.Mesh
          geometry={gltf.nodes.Cube_3_1.geometry}
          material={gltf.nodes.Cube_3_1.material}
          position={[-9.05, 0.45, 6.09]}
          rotation={[-0.25, 0.59, 0.14]}
          scale={[0.61, 0.42, 0.29]}
        />
      </T.Group>
      <T.Group position={[49.37, 267.49, 49.16]} rotation={[0, -0.2, -0.21]} scale={0.87}>
        <T.Mesh
          geometry={gltf.nodes.Cube_3_2.geometry}
          material={gltf.nodes.Cube_3_2.material}
          position={[-9.05, 0.45, 6.09]}
          rotation={[-0.25, 0.59, 0.14]}
          scale={[0.61, 0.42, 0.29]}
        />
      </T.Group>
      <T.Group position={[-72.77, 253.91, 36.37]} rotation={[-0.12, -0.18, -0.24]} scale={[-0.65, 0.61, 0.51]}>
        <T.Mesh
          geometry={gltf.nodes.Cube_2_1.geometry}
          material={gltf.nodes.Cube_2_1.material}
          rotation={[0, 0.58, 0]}
          scale={[1.35, 1.35, 0.82]}
        />
      </T.Group>
      <T.Group position={[-64.77, 243.38, 18.54]} rotation={[0, -0.2, -0.21]} scale={[-0.95, 0.9, 0.9]}>
        <T.Mesh
          geometry={gltf.nodes.Cube_2_2.geometry}
          material={gltf.nodes.Cube_2_2.material}
          rotation={[0, 0.58, 0]}
          scale={[1.35, 1.35, 0.82]}
        />
      </T.Group>
      <T.Group position={[36.4, 229.35, 56.95]} rotation={[-0.23, -0.15, -0.25]} scale={[0.63, 0.63, 0.52]}>
        <T.Mesh
          geometry={gltf.nodes.Cube_2_3.geometry}
          material={gltf.nodes.Cube_2_3.material}
          rotation={[0, 0.58, 0]}
          scale={[1.35, 1.35, 0.82]}
        />
      </T.Group>
      <T.Group position={[38.03, 220.59, 39.86]} rotation={[0, -0.2, -0.21]} scale={0.9}>
        <T.Mesh
          geometry={gltf.nodes.Cube_2_4.geometry}
          material={gltf.nodes.Cube_2_4.material}
          rotation={[0, 0.58, 0]}
          scale={[1.35, 1.35, 0.82]}
        />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.Cube_11.geometry}
        material={gltf.nodes.Cube_11.material}
        position={[-194.65, 136.09, 30.4]}
        rotation={[1.27, 0.2, 1.01]}
        scale={[0.34, 0.29, 0.3]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_9.geometry}
        material={gltf.nodes.Cube_9.material}
        position={[-24.71, 95.03, 135.49]}
        rotation={[Math.PI / 2, 0.36, 0]}
        scale={[0.34, 0.29, 0.3]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_11_1.geometry}
        material={gltf.nodes.Cube_11_1.material}
        position={[-159.84, 131.53, 76.35]}
        rotation={[1.94, -0.23, 1.03]}
        scale={[0.34, 0.29, 0.3]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_10.geometry}
        material={gltf.nodes.Cube_10.material}
        position={[32.83, 90.47, 131.92]}
        rotation={[Math.PI / 2, -0.43, 0]}
        scale={[0.34, 0.29, 0.3]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_11_2.geometry}
        material={gltf.nodes.Cube_11_2.material}
        position={[-183.06, 142.25, 57.01]}
        rotation={[Math.PI / 2, 0, 0.98]}
        scale={[0.34, 0.29, 0.3]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_8.geometry}
        material={gltf.nodes.Cube_8.material}
        position={[3.88, 101.19, 140.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.34, 0.29, 0.3]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_7.geometry}
        material={gltf.nodes.Cube_7.material}
        position={[-3.34, 229.94, -40.24]}
        rotation={[0, -0.2, -0.21]}
        scale={2.47}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_5.geometry}
        material={gltf.nodes.Cube_5.material}
        position={[-153.69, 343.37, -72.44]}
        rotation={[0, -0.21, -2.95]}
        scale={[1.41, 1.24, 1.41]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_4.geometry}
        material={gltf.nodes.Cube_4.material}
        position={[106.4, 4.34, -17.49]}
        rotation={[0, -0.2, 0.11]}
        scale={[1.41, 1.24, 1.41]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_2.geometry}
        material={gltf.nodes.Cube_2.material}
        position={[-21.67, 228.34, 62.37]}
        rotation={[-0.01, -0.23, -0.22]}
        scale={[-0.48, 0.2, 0.1]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
