<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /Users/nicoleac/Documents/dev/aura-sphere/static/models/Breathe.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      breathe: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/models/Breathe.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.DirectionalLight intensity={1} decay={2} rotation={[0.6, 0.6, -0.88]} />
      <T.DirectionalLight intensity={0.2} decay={2} rotation={[-2.04, -0.45, 1.35]} />
      <T.OrthographicCamera
        makeDefault={false}
        far={100000}
        near={0}
        position={[59.12, 85.53, 990.22]}
        rotation={[0.05, 0.1, 0]}
      />
      <T.Mesh geometry={gltf.nodes.breathe.geometry} material={gltf.nodes.breathe.material} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
