<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /Users/nicoleac/Documents/dev/aura-sphere/static/models/Friends.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube_8: THREE.Mesh
      Sphere_5: THREE.Mesh
      Sphere_4: THREE.Mesh
      Cube_14: THREE.Mesh
      Cube_13: THREE.Mesh
      Cube_12: THREE.Mesh
      Cube_12_1: THREE.Mesh
      Cube_10: THREE.Mesh
      Cube_9: THREE.Mesh
      Cylinder: THREE.Mesh
      Torus_2: THREE.Mesh
      Torus: THREE.Mesh
      Body: THREE.Mesh
      Sphere_3: THREE.Mesh
      Sphere_2: THREE.Mesh
      Sphere: THREE.Mesh
      Cube_5: THREE.Mesh
      Cube_7: THREE.Mesh
      Cube_6: THREE.Mesh
      Cube_4: THREE.Mesh
      Cube_3: THREE.Mesh
      Cube_2: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/models/Friends.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Group position={[55.18, 3.61, 219.64]} rotation={[-0.1, -0.3, -0.05]}>
        <T.Mesh
          geometry={gltf.nodes.Cube_8.geometry}
          material={gltf.nodes.Cube_8.material}
          position={[0.15, -9.58, 9.86]}
        />
        <T.Mesh
          geometry={gltf.nodes.Sphere_5.geometry}
          material={gltf.nodes.Sphere_5.material}
          position={[30.83, 24.04, 60.61]}
          scale={0.78}
        />
        <T.Mesh
          geometry={gltf.nodes.Sphere_4.geometry}
          material={gltf.nodes.Sphere_4.material}
          position={[-29.56, 24.04, 60.61]}
          scale={0.78}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_14.geometry}
          material={gltf.nodes.Cube_14.material}
          position={[-62.23, -26.56, 32.58]}
          rotation={[-2.9, -0.17, 0.47]}
          scale={0.27}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_13.geometry}
          material={gltf.nodes.Cube_13.material}
          position={[60.88, -22.67, 32.91]}
          rotation={[-3.12, 0.25, -0.47]}
          scale={0.27}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_12.geometry}
          material={gltf.nodes.Cube_12.material}
          position={[28.31, -66.41, 22.5]}
          rotation={[3.02, -0.03, -0.45]}
          scale={0.27}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_12_1.geometry}
          material={gltf.nodes.Cube_12_1.material}
          position={[-29.9, -66.22, 24.16]}
          rotation={[3.02, -0.03, 0.13]}
          scale={0.27}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_10.geometry}
          material={gltf.nodes.Cube_10.material}
          position={[0.52, 15.39, 65.03]}
          rotation={[-0.09, 0.85, 1.19]}
          scale={[0.88, 0.97, 1]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_9.geometry}
          material={gltf.nodes.Cube_9.material}
          position={[-1.4, 60.95, 25.99]}
          rotation={[0.68, 0.26, 0.62]}
        />
      </T.Group>
      <T.Group position={[1.1, 11.41, 23.19]}>
        <T.Group position={[-14.18, 77.12, 147.58]} rotation={[-0.22, 0, 0]} scale={0.51}>
          <T.Mesh
            geometry={gltf.nodes.Cylinder.geometry}
            material={gltf.nodes.Cylinder.material}
            position={[-24.8, 21.54, 0.39]}
            rotation={[0, -0.02, 0.08]}
          />
          <T.Mesh
            geometry={gltf.nodes.Torus_2.geometry}
            material={gltf.nodes.Torus_2.material}
            position={[-47.51, 17.38, 0]}
            rotation={[0, -0.02, 2.2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Torus.geometry}
            material={gltf.nodes.Torus.material}
            position={[-1.89, 20.99, 0.87]}
            rotation={[0, -0.02, 2.2]}
          />
        </T.Group>
        <T.Mesh
          geometry={gltf.nodes.Body.geometry}
          material={gltf.nodes.Body.material}
          position={[-19.44, -31.2, -23.27]}
          rotation={[0, 0, 0.09]}
        />
        <T.Mesh
          geometry={gltf.nodes.Sphere_3.geometry}
          material={gltf.nodes.Sphere_3.material}
          position={[51.11, 82.72, 117.21]}
          rotation={[0, 0, 0.09]}
        />
        <T.Mesh
          geometry={gltf.nodes.Sphere_2.geometry}
          material={gltf.nodes.Sphere_2.material}
          position={[-112.82, 68.48, 117.21]}
          rotation={[0, 0, 0.09]}
        />
        <T.Mesh
          geometry={gltf.nodes.Sphere.geometry}
          material={gltf.nodes.Sphere.material}
          position={[-8.1, -165.45, -186.91]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_5.geometry}
          material={gltf.nodes.Cube_5.material}
          position={[107.53, -78.29, 146.64]}
          rotation={[1.67, 0, -0.16]}
          scale={0.8}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_7.geometry}
          material={gltf.nodes.Cube_7.material}
          position={[71.21, -197.72, 36.96]}
          rotation={[3.02, -0.03, -0.45]}
          scale={0.8}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_6.geometry}
          material={gltf.nodes.Cube_6.material}
          position={[-101.62, -197.14, 41.89]}
          rotation={[3.02, -0.03, 0.13]}
          scale={0.8}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_4.geometry}
          material={gltf.nodes.Cube_4.material}
          position={[-30.17, -83.07, 168.16]}
          rotation={[1.67, 0, -0.4]}
          scale={0.8}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_3.geometry}
          material={gltf.nodes.Cube_3.material}
          position={[54.55, 225.36, 3.42]}
          rotation={[0, 0, -0.4]}
          scale={0.93}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_2.geometry}
          material={gltf.nodes.Cube_2.material}
          position={[-120.68, 212.02, -3.71]}
          rotation={[0, 0, 0.36]}
          scale={0.93}
        />
      </T.Group>
      <T.DirectionalLight intensity={0.7} decay={2} rotation={[-0.51, 0.63, 0.76]} />
      <T.OrthographicCamera
        makeDefault={false}
        far={100000}
        near={0}
        position={[-28.51, 179.86, 983.28]}
        rotation={[-0.18, -0.03, -0.01]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
