<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /Users/nicoleac/Documents/dev/aura-sphere/static/models/Rocket.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder_2: THREE.Mesh
      Cylinder: THREE.Mesh
      Cylinder_2_1: THREE.Mesh
      Cylinder_1: THREE.Mesh
      Shape: THREE.Mesh
      mesh_4_instance_1: THREE.Mesh
      mesh_4_instance_2: THREE.Mesh
      mesh_4_instance_3: THREE.Mesh
      Up: THREE.Mesh
      Body_White: THREE.Mesh
      bottom: THREE.Mesh
      Engine: THREE.Mesh
      Fire_Red: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/models/Rocket.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.DirectionalLight intensity={1} decay={2} rotation={[0.6, 0.6, -0.88]} />
      <T.DirectionalLight intensity={0.2} decay={2} rotation={[-2.04, -0.45, 1.35]} />
      <T.OrthographicCamera
        makeDefault={false}
        far={100000}
        near={0}
        position={[59.12, 85.53, 990.22]}
        rotation={[0.05, 0.1, 0]}
      />
      <T.Group position={[-0.04, 47.73, 45.55]} rotation={[-0.22, 0, 0]} scale={0.48}>
        <T.Mesh
          geometry={gltf.nodes.Cylinder_2.geometry}
          material={gltf.nodes.Cylinder_2.material}
          position={[0.01, -0.35, 4.36]}
          rotation={[1.61, 0.03, 0]}
          scale={[0.71, 0.34, 0.71]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder.geometry}
          material={gltf.nodes.Cylinder.material}
          position={[0, 0, -5.6]}
          rotation={[1.61, 0.03, 0]}
          scale={[0.89, 1, 0.89]}
        />
      </T.Group>
      <T.Group position={[-0.04, 2.75, 47.44]} scale={0.48}>
        <T.Mesh
          geometry={gltf.nodes.Cylinder_2_1.geometry}
          material={gltf.nodes.Cylinder_2_1.material}
          position={[0.01, -0.35, 4.36]}
          rotation={[1.61, 0.03, 0]}
          scale={[0.71, 0.34, 0.71]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder_1.geometry}
          material={gltf.nodes.Cylinder_1.material}
          position={[0, 0, -5.6]}
          rotation={[1.61, 0.03, 0]}
          scale={[0.89, 1, 0.89]}
        />
      </T.Group>
      <T.Group position={[-2, -11.79, 0.84]} scale={0.48}>
        <T.Mesh
          geometry={gltf.nodes.Shape.geometry}
          material={gltf.nodes.Shape.material}
          position={[91.88, 14.97, 35.66]}
          rotation={[0.02, -0.47, -0.69]}
          scale={[0.34, 0.32, 0.28]}
        />
      </T.Group>
      <T.Group position={[-2, -11.79, 0.84]} scale={0.48}>
        <T.Group rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
          <T.Mesh
            geometry={gltf.nodes.mesh_4_instance_2.geometry}
            material={gltf.nodes.mesh_4_instance_2.material}
            position={[91.88, 14.97, 35.66]}
            rotation={[0.02, -0.47, -0.69]}
            scale={[0.34, 0.32, 0.28]}
          />
        </T.Group>
        <T.Group rotation={[-Math.PI, Math.PI / 3, -Math.PI]}>
          <T.Mesh
            geometry={gltf.nodes.mesh_4_instance_3.geometry}
            material={gltf.nodes.mesh_4_instance_3.material}
            position={[91.88, 14.97, 35.66]}
            rotation={[0.02, -0.47, -0.69]}
            scale={[0.34, 0.32, 0.28]}
          />
        </T.Group>
        <T.Mesh
          geometry={gltf.nodes.mesh_4_instance_1.geometry}
          material={gltf.nodes.mesh_4_instance_1.material}
          position={[91.88, 14.97, 35.66]}
          rotation={[0.02, -0.47, -0.69]}
          scale={[0.34, 0.32, 0.28]}
        />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.Up.geometry}
        material={gltf.nodes.Up.material}
        position={[-0.38, 17.49, -4.98]}
        rotation={[0, 0, 0.03]}
        scale={0.37}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_White.geometry}
        material={gltf.nodes.Body_White.material}
        position={[-0.36, 17.22, -4.71]}
        rotation={[0, 0, 0.03]}
        scale={0.39}
      />
      <T.Mesh
        geometry={gltf.nodes.bottom.geometry}
        material={gltf.nodes.bottom.material}
        position={[1.31, -36.27, -4.08]}
        rotation={[0, 0, 0.03]}
        scale={0.38}
      />
      <T.Mesh
        geometry={gltf.nodes.Engine.geometry}
        material={gltf.nodes.Engine.material}
        position={[1.11, -42.75, -4.07]}
        rotation={[Math.PI / 2, 0.03, 0]}
        scale={[0.41, 0.41, 0.81]}
      />
      <T.Mesh
        geometry={gltf.nodes.Fire_Red.geometry}
        material={gltf.nodes.Fire_Red.material}
        position={[2.51, -75.13, -4.31]}
        rotation={[0, 0, 0.03]}
        scale={[0.32, 0.41, 0.32]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
